version: "3"
services:

  postgres:
    image: postgres:10.2
    restart: always
    environment:
      POSTGRES_USER: spendy
      POSTGRES_PASSWORD: spendy
    ports:
      - '5432:5432'
    

  spendy:
    build: . # calls on the directory Dockerfile
    command: python -m unittest discover   
    
    environment:
      PYTHONUNBUFFERED: "true"
      APP_ENVIRONMENT: TESTING
      FLASK_CONFIG: config/testing.py
      DATABASE_NAME: spendy_testing
      
    links:
      - postgres
    depends_on:
      - postgres #make sure it's on before starting this one

    
    volumes:
      - .:/spendy
    ports:
      - '8000:8000'
      - '5000:5000'