

INSERT INTO "categories" (name, label, user_id) VALUES
    ('peluqueria', 'Peluquería', 4),
    ('comer_fuera', 'Comer Fuera', 4),
    ('taxi', 'Taxi', 4),
    ('compras', 'Compras', 4),
    ('otros', 'Otros', 4),
    ('viajes', 'Viajes', 4),
    ('alcohol', 'Alcohol', 4),
    ('salir_noche', 'Salir (Noche)', 4),
    ('salud', 'Salud', 4),
    ('ropa', 'Ropa', 4),
    ('regalos', 'Regalos', 4),
    ('luz', 'Luz', 4),
    ('mantenimiento', 'Mantenimiento', 4),
    ('celulares', 'Celulares', 4),
    ('empleados', 'Empleados', 4),
    ('internet', 'Internet', 4),
    ('servicios_online', 'Servicios Online', 4),
    ('alquiler', 'Alquiler', 4),
    ('supervision', 'Supervisión', 4),
    ('cine', 'Cine', 4),
    ('juegos', 'Juegos', 4),
    ('lavanderia', 'Lavandería', 4),
    ('hogar', 'Hogar', 4),
    ('mascotas', 'Mascotas', 4),
    ('consultorio', 'Consultorio', 4),
    ('impuestos', 'Impuestos', 4),
    ('programacion', 'Programación', 4),
    ('comics', 'Comics', 4),
    ('belleza', 'Belleza', 4),
    ('deporte', 'Deporte', 4);