BASE_URL = 'http://127.0.0.1:5000'

TEST_VALID_USER = 'Testing guy'
TEST_VALID_EMAIL = 'test@guy.com'
TEST_VALID_PASSWORD = 'letrasyn234ros!'

TEST_INVALID_USER = ''
TEST_INVALID_EMAIL = 'test@a'
TEST_INVALID_PASSWORD = 'corto'

TEST_VALID_CATEGORY_NAME = 'Compras'
TEST_INVALID_CATEGORY_NAME = ''

TEST_VALID_EXPENSE_NAME = 'Beer'
TEST_VALID_EXPENSE_AMOUNT = '10.03'

TEST_INVALID_EXPENSE_NAME = ''
TEST_INVALID_NEGATIVE_EXPENSE_AMOUNT = '-23.0'
TEST_INVALID_TEXT_EXPENSE_AMOUNT = 'text'

TEST_VALID_MONTH_ID = 2018011