"""empty message

Revision ID: 08a2b37f37e0
Revises: 789176ab6a9e
Create Date: 2018-02-01 16:01:17.812451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a2b37f37e0'
down_revision = '789176ab6a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('label', sa.Unicode(length=50), nullable=False))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('categories', 'label')
    # ### end Alembic commands ###
