"""empty message

Revision ID: 40ef3b75c865
Revises: 08a2b37f37e0
Create Date: 2018-02-01 17:31:06.205175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ef3b75c865'
down_revision = '08a2b37f37e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('months',
    sa.Column('year_month_usr', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('year_month_usr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('months')
    # ### end Alembic commands ###
