"""empty message

Revision ID: 5b0766c8bd86
Revises: 40ef3b75c865
Create Date: 2018-02-01 17:32:48.679830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0766c8bd86'
down_revision = '40ef3b75c865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('month_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'months', ['month_id'], ['year_month_usr'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'month_id')
    # ### end Alembic commands ###
